### ISSUE TITLE
License feature doesnt work in CLion

### ISSUE THREAD

**Issue by wmmc88** [Noam-Dori/ros-integrate#53]
**Describe the bug**
https://github.com/Noam-Dori/ros-integrate/issues/52#issuecomment-716621973
After installing the latest version of the plugin available on Clion, opening a package.xml and ctrl+clicking a license value does not do anything. 

**To Reproduce**
1. Go to a package.xml
2. Ctrl+Click a license

**Expected behavior**
I believe its suppposed to give me a tldr of the license or open a browser to a copy of that license

**Environment Information:**
 - OS: Ubuntu 20.04.1
 - IDE: CLion 2020.2.4
 - Plugin Version: 0.1.6
 - Related Plugins: No other plugins are installed currently

**Stack Trace**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/16629657/97223414-1b99b400-17a6-11eb-96d9-d1f9264b615c.png)
![image](https://user-images.githubusercontent.com/16629657/97223686-7c28f100-17a6-11eb-97e7-4f4fc35904dc.png)

**Additional context**
N/A

**Comment by Noam-Dori** [comment]
Looking at the screenshot, the issue is caused by the plugin not recognizing `uwrt_mars_rover_hw` as a ROS package (otherwise in the project view it will be seen as a blue folder).

I could not replicate the bug on my end. However, I do have several questions that can help resolve the issue:
- are the packages correctly found after restarting the IDE, or does the plugin only find random (but not all) packages?
- In the external libraries tab, is there a library called ROS? are the packages in it colored orange?

Related issues: PR #41

**Comment by Noam-Dori** [comment]
Closed due to inactivity.
